### ISSUE TITLE
Index out of range error at copyReversed function

### ISSUE THREAD

**Issue by L11R** [ProtonMail/crypto#23]
Sometimes getting this:
```runtime error: index out of range
goroutine 295 [running]:
net/http.(*conn).serve.func1(0xc0000b5a40)
	/usr/lib/golang/src/net/http/server.go:1769 +0x139
panic(0x8a1a80, 0xd9d180)
	/usr/lib/golang/src/runtime/panic.go:522 +0x1b5
golang.org/x/crypto/openpgp/ecdh.copyReversed(0xc0008431b0, 0x20, 0x20, 0xc0006ea5c0, 0x1f, 0x1f)
	/home/savely/go/pkg/mod/github.com/!proton!mail/crypto@v0.0.0-20190604143603-d3d8a14a4d4f/openpgp/ecdh/x25519.go:144 +0x112
golang.org/x/crypto/openpgp/ecdh.X25519Decrypt(0xc00045ede0, 0xc0003a8b10, 0x21, 0x21, 0xc0003a8b40, 0x30, 0x30, 0xc000785420, 0xb, 0x10, ...)
	/home/savely/go/pkg/mod/github.com/!proton!mail/crypto@v0.0.0-20190604143603-d3d8a14a4d4f/openpgp/ecdh/x25519.go:112 +0x17a
golang.org/x/crypto/openpgp/ecdh.Decrypt(0xc00045ede0, 0xc0003a8b10, 0x21, 0x21, 0xc0003a8b40, 0x30, 0x30, 0xc000785420, 0xb, 0x10, ...)
	/home/savely/go/pkg/mod/github.com/!proton!mail/crypto@v0.0.0-20190604143603-d3d8a14a4d4f/openpgp/ecdh/ecdh.go:91 +0x4a1
golang.org/x/crypto/openpgp/packet.(*EncryptedKey).Decrypt(0xc00017eaf0, 0xc00018fe00, 0xc0002f02a0, 0x0, 0x0)
	/home/savely/go/pkg/mod/github.com/!proton!mail/crypto@v0.0.0-20190604143603-d3d8a14a4d4f/openpgp/packet/encrypted_key.go:111 +0x4e8
golang.org/x/crypto/openpgp.ReadMessage(0x9c63e0, 0xc0002c0870, 0x9cf520, 0xc00068ec20, 0x0, 0xc0002f02a0, 0x1, 0x1, 0xc0002c0870)
	/home/savely/go/pkg/mod/github.com/!proton!mail/crypto@v0.0.0-20190604143603-d3d8a14a4d4f/openpgp/read.go:161 +0xca3
github.com/ProtonMail/gopenpgp/crypto.asymmetricDecrypt(0x9c63e0, 0xc0002c0870, 0xc0003001e0, 0xc0003bbf20, 0x5d1b3ec9, 0xc01b418690, 0x58789950045dd, 0xc000843860, 0x7c931f, 0xbf3eed925b418690, ...)
	/home/savely/go/pkg/mod/github.com/!proton!mail/gopenpgp@v1.0.1-0.20190613082613-552ce9554f87/crypto/keyring_message.go:140 +0x1b3
github.com/ProtonMail/gopenpgp/crypto.(*KeyRing).Decrypt(0xc0003001e0, 0xc00068ec00, 0xc0003bbf20, 0x5d1b3ec9, 0x0, 0x0, 0xc000843900, 0x448ac0)
	/home/savely/go/pkg/mod/github.com/!proton!mail/gopenpgp@v1.0.1-0.20190613082613-552ce9554f87/crypto/keyring_message.go:40 +0xe2
```
Function itself:
```go
func copyReversed(out []byte, in []byte) {
	for i := 31; i >= 0; i-- {
		out[31-i] = in[i]
	}
}
```
Sometimes `in` length is 31.

**Comment by L11R** [comment]
Invalid 31 length bytes are assigned here:
https://github.com/ProtonMail/crypto/blob/d3d8a14a4d4f772c205a10c24d14676522ee95d2/openpgp/packet/private_key.go#L572

**Comment by L11R** [comment]
Seems like problem is again related to MPI encoding/decoding #22

**Comment by L11R** [comment]
This crippy workaround seems to be helpful for me:
```go
if len(ecdhPriv.D) == 31 {
	ecdhPriv.D = append([]byte{0}, ecdhPriv.D...)
}
```
But I don't think it should fixed that way.

**Comment by L11R** [comment]
I wrote simple client-server testing environment to reproduce this problem easily:
Golang Server: https://gist.github.com/L11R/fa3abf28fc199bb4e5231ad8bb3d83d9
Node.js Client: https://gist.github.com/L11R/4e79f1c7716fc524b09c9ab9aba446d0

**Comment by L11R** [comment]
@twiss any news?

**Comment by twiss** [comment]
Hi @L11R - sorry for the really long delay! And also thanks for reporting this issue! The above PR should fix it.

**Comment by L11R** [comment]
@twiss thanks for answer and providing fix. We really tried to integrate OpenPGP solution into our service, but ended up with writing custom ECIES solution: https://github.com/ecies/go 

Hope your libraries will be more mature for production use in near future.

**Comment by twiss** [comment]
Sure. I think that's fine, if you don't need compatibility with the OpenPGP (email) ecosystem then going with something simpler is not necessarily always a bad thing.
