### ISSUE TITLE
AEAD Encrypt fails for long plaintexts

### ISSUE THREAD

**Issue by zugzwang** [ProtonMail/crypto#43]
## Current bug behavior

The message encrypting function `openpgp.Encrypt` panics on `Write` for long plaintext messages. 
When calling `openpgp.Encrypt` on plaintexts of length around `1<<20`, `EndToEndTest` fails with
```
	panic: bytes.Buffer.WriteTo: invalid Write count
```
(see the whole stack trace below)

## Expected behavior 

`TestEndToEnd` should be able to encrypt messages of this size and larger.

## How to reproduce

Go to `openpgp/integration_tests/utils_test.go` function `randMessage()` and increase the size of random test messages:
```
	maxMessageLength := 1 << 20
```
(previous value set at `1 << 12`), and run the test:

```go test ./... -run EndToEnd```

## Posible cause

Definitely related to `AEADEncrypted` writer or closer, according to the stack trace, which is in turn related to the implementation of `partialLengthWriter`. The panic arises when closing a `partialLengthWriter`.

Also, there's no panic if AEAD is disabled (indicated by the absence of a `packet.AEADConfig` inside the `packet.Config` passed to `openpgp.Encrypt`).

## Posible fix

WIP

## Related PRs

#36 - Aead packet support.

## Complete traceback
```
=== RUN   TestEndToEnd/rsa_foreign/encryptDecrypt/ed25519_fresh
panic: bytes.Buffer.WriteTo: invalid Write count [recovered]
	panic: bytes.Buffer.WriteTo: invalid Write count

goroutine 69 [running]:
testing.tRunner.func1(0xc0000b6500)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x600d00, 0x691f40)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
bytes.(*Buffer).WriteTo(0xc0000749d0, 0x7fbf723016b8, 0xc00004a210, 0x7fbf723016b8, 0xc00004a210, 0xc00032a4e0)
	/usr/local/go/src/bytes/buffer.go:241 +0x145
golang.org/x/crypto/openpgp/packet.(*partialLengthWriter).Close(0xc0000749c0, 0x69a180, 0xc00007a000)
	/home/botvinnik/go/src/golang.org/x/crypto/openpgp/packet/packet.go:135 +0xd5
golang.org/x/crypto/openpgp.signatureWriter.Close(0x698000, 0xc0000a2280, 0x698040, 0xc0000749c0, 0x5, 0x69a180, 0xc00007a000, 0x69a180, 0xc00007a000, 0xc000001c80, ...)
	/home/botvinnik/go/src/golang.org/x/crypto/openpgp/write.go:462 +0x140
golang.org/x/crypto/openpgp/integration_tests.encDecTest.func1(0xc0000b6500)
	/home/botvinnik/go/src/golang.org/x/crypto/openpgp/integration_tests/end_to_end_test.go:175 +0x3e2
testing.tRunner(0xc0000b6500, 0xc00031a000)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
exit status 2
FAIL	golang.org/x/crypto/openpgp/integration_tests	1.393s
```

**Comment by zugzwang** [comment]
Since the is present only in the code provided in #36, this issue is closed in favor of a comment in that PR.
